"""Add user blocking functionality and update levels

Revision ID: 37d8d6b896b8
Revises: f7e53dc25c04
Create Date: 2025-09-06 15:08:16.519081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d8d6b896b8'
down_revision = 'f7e53dc25c04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing records
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('blocked_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('blocked_reason', sa.String(length=255), nullable=True))
    
    # Update existing users to have level 0 instead of 1 (if any have level 1)
    op.execute("UPDATE \"user\" SET level = 0 WHERE level = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blocked_reason')
    op.drop_column('user', 'blocked_at')
    op.drop_column('user', 'is_blocked')
    # ### end Alembic commands ###
