"""Remove is_advanced field from user table

Revision ID: 80419fd9aa55
Revises: d2a3863d3255
Create Date: 2025-09-06 22:00:31.122688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80419fd9aa55'
down_revision = 'd2a3863d3255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_advanced')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_advanced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
