"""Add password_changed field to Admin model

Revision ID: a8666d270528
Revises: 
Create Date: 2025-09-06 14:41:28.724105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8666d270528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing records
    op.add_column('admin', sa.Column('password_changed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_changed')
    # ### end Alembic commands ###
