"""Ensure unique constraints on username and email fields

Revision ID: f7e53dc25c04
Revises: a8666d270528
Create Date: 2025-09-06 14:49:46.350567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e53dc25c04'
down_revision = 'a8666d270528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
